name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  test:
    uses: Uzlopak/workflows/.github/workflows/plugins-ci.yml@license-check-additional
    with:
      license-check: true
      license-check-allowed-additional: CC-BY-4.0
